@ECHO ON
rmdir /Q /S "public_html/includes"
rmdir /Q /S "public_html/misc"
rmdir /Q /S "public_html/modules"
rmdir /Q /S "public_html/profiles"
rmdir /Q /S "public_html/scripts"
rmdir /Q /S "public_html/themes"
cd public_html
del ".editorconfig"
del "authorize.php"
del "CHANGELOG.txt"
del "COPYRIGHT.txt"
del "cron.php"
del "index.php"
del "install.php"
del "INSTALL.mysql.txt"
del "INSTALL.pgsql.txt"
del "INSTALL.sqlite.txt"
del "INSTALL.txt"
del "LICENSE.txt"
del "MAINTAINERS.txt"
del "PATCHES.txt"
del "README.txt"
del "update.php"
del "UPGRADE.txt"
del "xmlrpc.php"
ECHO Remember to apply patches if ther are any!
PAUSE
