version: '3'

services:
  db:
    image: mariadb:10.3
    container_name: mariadb
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: AppleSucks
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  # sqlsrv:
  #   image: microsoft/mssql-server-linux:2017-latest
  #   container_name: sqlsrv
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: admin!@2super
  #   volumes:
  #     - ./sql_data:/var/opt/mssql
  drupal:
    depends_on:
      - db
      # - sqlsrv
    build:
      context: .
      # args:
        # PROXY: ${PROXY}
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html
      - ./logs/apache2:/var/log/apache2/
    links:
      - "db"
      # - "sqlsrv"
volumes:
  db_data: